name: Prettier

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: PNPM Setup
        uses: pnpm/action-setup@v4
        with:
          version: "latest"

      - name: Install Dependencies
        run: pnpm install

      - name: Format Code
        run: pnpm format

      - name: Commit formatted code
        uses: EndBug/add-and-commit@v9
        with:
          author_name: "github-actions"
          author_email: "github-actions@github.com"
          message: "Chore : Format Code"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
