name: ESLint

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: PNPM Setup
        uses: pnpm/action-setup@v2
        with:
          version: "latest"

      - name: Install Dependencies
        run: pnpm install

      - name: Lint Code
        run: pnpm lint
